/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface Configschema {
  /**
   * This toggles if on the 1st/2nd stream if applicable for your event.
   */
  thisEvent: number;
  obs: {
    address: string;
    password: string;
    /**
     * Name of the scene in OBS you wish to run commercials on when switched to.
     */
    commercialScene: string;
  };
}
