/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface Configschema {
	/**
	 * This toggles if on the 1st/2nd stream if applicable for your event.
	 */
	thisEvent: number;
	obs: {
		address: string;
		password: string;
		/**
		 * Name of the scene in OBS you wish to start running non-run based commercials on when switched to.
		 */
		nonRunCommercialTriggerScene: string;
		/**
		 * Name(s) of the scene(s) in OBS you wish to allow non-run based commercials to continue running on.
		 */
		nonRunCommercialScenes: string | string[];
	};
}
